accent = "#42be65"
cursor = "#f2f4f8"
foreground = "#f2f4f8"
background = "#161616"
selection_foreground = "#E1E1E6"
selection_background = "#41414D"

color0 = "#161616"
color1 = "#3ddbd9"
color2 = "#33b1ff"
color3 = "#ee5396"
color4 = "#42be65"
color5 = "#be95ff"
color6 = "#ff7eb6"
color7 = "#f2f4f8"
color8 = "#525252"
color9 = "#78a9ff"
color10 = "#262626"
color11 = "#393939"
color12 = "#dde1e6"
color13 = "#ffffff"
color14 = "#82cfff"
color15 = "#08bdba"
