
# ========= Border =========
file_panel_border = '#f2f4f8'
sidebar_border = '#f2f4f8'
footer_border = '#f2f4f8'

# ========= Border Active =========
file_panel_border_active = '#42be65'
sidebar_border_active = '#42be65'
footer_border_active = '#42be65'
modal_border_active = '#42be65'

# ========= Background (bg) =========
full_screen_bg = '#161616'
file_panel_bg = '#161616'
sidebar_bg = '#161616'
footer_bg = '#161616'
modal_bg = '#161616'

# ========= Foreground (fg) =========
full_screen_fg = '#f2f4f8'
file_panel_fg = '#f2f4f8'
sidebar_fg = '#f2f4f8'
footer_fg = '#f2f4f8'
modal_fg = '#f2f4f8'

# ========= Special Color =========
cursor = '#f2f4f8'
correct = '#33b1ff'
error = '#3ddbd9'
hint = '#ff7eb6'
cancel = '#3ddbd9'
gradient_color = ['#161616', "#525252"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#161616'
file_panel_top_path = '#525252'
file_panel_item_selected_fg = '#525252'
file_panel_item_selected_bg = '#161616'

# ========= Sidebar Special Items =========
sidebar_title = '#08bdba'
sidebar_item_selected_fg = '#525252'
sidebar_item_selected_bg = '#161616'
sidebar_divider = '#f2f4f8'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#3ddbd9'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#33b1ff'
